Parameters:
  model:
    Type: String
    Default: ""
  task:
    Type: String
Resources:
  hfsagemakerexecutionrole6481FA1C:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: HuggingfaceSagemaker/hf_sagemaker_execution_role/Resource
  hfsagemakerexecutionroleDefaultPolicyC67188A8:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - sagemaker:*
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
              - ecr:GetAuthorizationToken
              - cloudwatch:PutMetricData
              - cloudwatch:GetMetricData
              - cloudwatch:GetMetricStatistics
              - cloudwatch:ListMetrics
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:DescribeLogStreams
              - logs:PutLogEvents
              - logs:GetLogEvents
              - s3:CreateBucket
              - s3:ListBucket
              - s3:GetBucketLocation
              - s3:GetObject
              - s3:PutObject
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: hfsagemakerexecutionroleDefaultPolicyC67188A8
      Roles:
        - Ref: hfsagemakerexecutionrole6481FA1C
    Metadata:
      aws:cdk:path: HuggingfaceSagemaker/hf_sagemaker_execution_role/DefaultPolicy/Resource
  hfmodel:
    Type: AWS::SageMaker::Model
    Properties:
      ExecutionRoleArn:
        Fn::GetAtt:
          - hfsagemakerexecutionrole6481FA1C
          - Arn
      ModelName:
        Fn::Join:
          - ""
          - - model-
            - Ref: model
      PrimaryContainer:
        Environment:
          HF_MODEL_ID:
            Ref: model
          HF_TASK:
            Ref: task
        Image: 763104351884dkr.ecr.us-east-1.amazonaws.com/huggingface-pytorch-inference:1.7.1-transformers4.6.1-cpu-py36-ubuntu18.04
    Metadata:
      aws:cdk:path: HuggingfaceSagemaker/hf_model
  hfendpointconfig:
    Type: AWS::SageMaker::EndpointConfig
    Properties:
      ProductionVariants:
        - InitialInstanceCount: 1
          InitialVariantWeight: 1
          InstanceType: ml.m5.xlarge
          ModelName:
            Fn::Join:
              - ""
              - - model-
                - Ref: model
          VariantName:
            Fn::Join:
              - ""
              - - model-
                - Ref: model
      EndpointConfigName:
        Fn::Join:
          - ""
          - - config-
            - Ref: model
    Metadata:
      aws:cdk:path: HuggingfaceSagemaker/hf_endpoint_config
  hfendpoint:
    Type: AWS::SageMaker::Endpoint
    Properties:
      EndpointConfigName:
        Fn::Join:
          - ""
          - - config-
            - Ref: model
      EndpointName:
        Fn::Join:
          - ""
          - - endpoint-
            - Ref: model
    Metadata:
      aws:cdk:path: HuggingfaceSagemaker/hf_endpoint
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/02MwQqDMBBEv6X3uNZKoceC9FgQ+wVLXO1Wky1JpEjIv9fYS08zvMdMBdWphuPhih9f6H4qoxZHEB8B9aSawbbo0FAgpxqxPrhFh4w78rI4TUnlYWQ0EDuZaXc5W5lZr/vD3pLyOJLBiRzEjd6lpznrm+3fwjZs9wOP/ySlpNo1PMWWNVzgfHh55sItNrAh6H75BY5YpqTBAAAA
    Metadata:
      aws:cdk:path: HuggingfaceSagemaker/CDKMetadata/Default

